name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    
    - name: Generate coverage report
      run: |
        pytest --cov=src/ --cov-report=xml

    - name: cat coverage report
      run: |
        cat coverage.xml
        pwd
        ls -al

    - name: Set up Java (required for SonarCloud)
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.organization=kobystestorg
          -Dsonar.projectKey=CustomizableBlackjack
          -Dsonar.sources=src/
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
