name: Run Tests & Do SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    
    - name: Pytest tests
      run: |
        pytest test/

    - name: Generate coverage report
      run: |
        pytest --cov=src/ --cov-report=xml

    - name: Verify coverage report
      run: ls -l coverage.xml

    - name: Set up Java (required for SonarCloud)
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up sonar-scanner
      run: |
        export SONAR_SCANNER_VERSION=6.1.0.4477
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"

    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
        -Dsonar.organization=kobystestorg \
        -Dsonar.projectKey=CustomizableBlackjack \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.python.coverage.reportPaths=coverage.xml
